# Docker Compose Override for Development
# This file is automatically loaded by docker-compose
version: '3.8'

services:
  backend:
    environment:
      NODE_ENV: development
    volumes:
      - ./apps/backend:/app/apps/backend
      - ./packages:/app/packages
    command: ["pnpm", "run", "dev"]
