[build]
builder = "heroku/builder:20"

[[build.buildpacks]]
uri = "heroku/nodejs-engine"

[[build.buildpacks]]  
uri = "heroku/nodejs-corepack"

[[build.buildpacks]]
uri = "heroku/nodejs-pnpm-install"

[build.env]
NODE_ENV = "production"