[project]
name = 'stackspay-contracts'
description = ''
authors = []
telemetry = true
cache_dir = './.cache'
requirements = []
[contracts.fee-collection]
path = 'contracts/fee-collection.clar'
clarity_version = 3
epoch = 'latest'

[contracts.merchant-registry]
path = 'contracts/merchant-registry.clar'
clarity_version = 3
epoch = 'latest'

[contracts.oracle-integration]
path = 'contracts/oracle-integration.clar'
clarity_version = 3
epoch = 'latest'

[contracts.payment-escrow]
path = 'contracts/payment-escrow.clar'
clarity_version = 3
epoch = 'latest'

[contracts.treasury]
path = 'contracts/treasury.clar'
clarity_version = 3
epoch = 'latest'
[repl.analysis]
passes = ['check_checker']

[repl.analysis.check_checker]
strict = false
trusted_sender = false
trusted_caller = false
callee_filter = false

[repl.remote_data]
enabled = false
api_url = 'https://api.hiro.so'
