apiVersion: koyeb.com/v1
kind: Service
metadata:
  name: stackspay-backend-staging
spec:
  # Service configuration
  name: stackspay-backend-staging
  type: web
  
  # Build configuration for monorepo
  build:
    type: docker
    docker:
      dockerfile: apps/backend/Dockerfile
      context: .
      target: production
    
  # Runtime configuration - smaller resources for staging
  instance_type: nano
  scaling:
    min: 1
    max: 1
  
  # Health check
  health_check:
    http:
      path: /health
      port: 3000
    initial_delay_seconds: 30
    timeout_seconds: 10
    
  # Port configuration
  ports:
    - port: 3000
      protocol: http
      public: true
      
  # Environment variables for staging
  env:
    - name: NODE_ENV
      value: staging
    - name: PORT
      value: "3000"
    # Database
    - name: DATABASE_URL
      from: secret
      secret_name: DATABASE_URL_STAGING
    - name: REDIS_URL
      from: secret
      secret_name: REDIS_URL_STAGING
    # Stacks/Bitcoin - using testnet for staging
    - name: STACKS_NETWORK
      value: testnet
    - name: STACKS_API_URL
      value: https://api.testnet.hiro.so
    # Security
    - name: JWT_SECRET
      from: secret
      secret_name: JWT_SECRET_STAGING
    - name: ENCRYPTION_KEY
      from: secret
      secret_name: ENCRYPTION_KEY_STAGING
    # API Keys
    - name: WEBHOOK_SECRET
      from: secret
      secret_name: WEBHOOK_SECRET_STAGING
    # Enable debug logging in staging
    - name: DEBUG
      value: "stackspay:*"
      
  # Resource limits - smaller for staging
  resources:
    memory: 256Mi
    cpu: 0.1
    
  # Regions
  regions:
    - fra # Frankfurt