[network]
name = "devnet"
deployment_fee_rate = 10

[accounts.deployer]
# mnemonic = "your-12-word-mnemonic-here"
balance = 100_000_000_000_000
sbtc_balance = 1_000_000_000

[accounts.wallet_1]
# mnemonic = "your-12-word-mnemonic-here"
balance = 100_000_000_000_000
sbtc_balance = 1_000_000_000

[accounts.wallet_2]
# mnemonic = "your-12-word-mnemonic-here"
balance = 100_000_000_000_000
sbtc_balance = 1_000_000_000

[accounts.wallet_3]
# mnemonic = "your-12-word-mnemonic-here"
balance = 100_000_000_000_000
sbtc_balance = 1_000_000_000

[accounts.wallet_4]
# mnemonic = "your-12-word-mnemonic-here"
balance = 100_000_000_000_000
sbtc_balance = 1_000_000_000

[accounts.wallet_5]
# mnemonic = "your-12-word-mnemonic-here"
balance = 100_000_000_000_000
sbtc_balance = 1_000_000_000

[accounts.wallet_6]
# mnemonic = "your-12-word-mnemonic-here"
balance = 100_000_000_000_000
sbtc_balance = 1_000_000_000

[accounts.wallet_7]
# mnemonic = "your-12-word-mnemonic-here"
balance = 100_000_000_000_000
sbtc_balance = 1_000_000_000

[accounts.wallet_8]
# mnemonic = "your-12-word-mnemonic-here"
balance = 100_000_000_000_000
sbtc_balance = 1_000_000_000

[accounts.faucet]
# mnemonic = "your-12-word-mnemonic-here"
balance = 100_000_000_000_000
sbtc_balance = 1_000_000_000

[devnet]
disable_stacks_explorer = false
disable_stacks_api = false

# Send some stacking orders
[[devnet.pox_stacking_orders]]
start_at_cycle = 1
duration = 10
auto_extend = true
wallet = "wallet_1"
slots = 2
btc_address = "mr1iPkD9N3RJZZxXRk7xF9d36gffa6exNC"

[[devnet.pox_stacking_orders]]
start_at_cycle = 1
duration = 10
auto_extend = true
wallet = "wallet_2"
slots = 2
btc_address = "muYdXKmX9bByAueDe6KFfHd5Ff1gdN9ErG"

[[devnet.pox_stacking_orders]]
start_at_cycle = 1
duration = 10
auto_extend = true
wallet = "wallet_3"
slots = 2
btc_address = "mvZtbibDAAA3WLpY7zXXFqRa3T4XSknBX7"